---
  username:
    description: "Username used to authenticate."
    type: "string"
    secret: false
    required: true
    default: "admin"
  password:
    description: "Password used to authenticate."
    type: "string"
    secret: true
    required: true
  sensorport:
    description: "Sensor port for Swagger"
    type: "integer"
    secret: false
    required: true
    default: 12021
  sensor2port:
    description: "Sensor port for Swagger2"
    type: "integer"
    secret: false
    required: true
    default: 12022
