---
  username:
    description: "Username used to authenticate."
    type: "string"
    secret: false
    required: true
    default: "admin"
  password:
    description: "Password used to authenticate."
    type: "string"
    secret: true
    required: true
